=== AppertaFoundation/openeyes/protected/config/core/OE_ED_CONFIG.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 3 (x64) (http://www.altova.com) by Jason Brown (Department of Health and Ageing) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    attributeFormDefault="unqualified">
    <xs:complexType name="INDEX_TYPE">
        <xs:sequence>
            <xs:element name="TERM_LIST">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="TERM" type="xs:string" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element minOccurs="0" name="IMG_URL" type="xs:string"/>
            <xs:element name="INDEX_LIST" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="INDEX" type="INDEX_TYPE" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="OE_ED_CONFIG">
        <xs:annotation>
            <xs:documentation>Comment describing your root element</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="CANVAS_LIST">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="CANVAS" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="CANVAS_MNEMONIC" type="xs:string"/>
                                        <xs:element name="CANVAS_NAME" type="xs:string"/>
                                        <xs:element name="OE_ELEMENT_CLASS_NAME" type="xs:string">
                                            <xs:annotation>
                                                <xs:documentation>Used to look up
                                                  openeyes.element_type.ID</xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="DOODLE_LIST">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="DOODLE" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="EYEDRAW_CLASS_MNEMONIC" type="xs:string"/>
                                        <xs:element name="TITLE" type="xs:string"/>
                                        <xs:element name="INIT_DOODLE_JSON" type="xs:string"
                                            nillable="true"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="DOODLE_USAGE_LIST">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="DOODLE_USAGE" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="EYEDRAW_CLASS_MNEMONIC" type="xs:string"/>
                                        <xs:element name="CANVAS_MNEMONIC" type="xs:string"/>
                                        <xs:element name="ON_TOOLBAR_LOCATION" type="xs:string"/>
                                        <xs:element name="ON_TOOLBAR_ORDER" type="xs:string"/>
                                        <xs:element name="NEW_EYE_INIT_FLAG" type="xs:boolean">
                                            <xs:annotation>
                                                <xs:documentation>These doodles are initialised if
                                                  nothing is known about patient
                                                  eye.</xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                        <xs:element name="CARRY_FORWARD_FLAG" type="xs:boolean"/>
                                        <xs:element name="CONDITIONAL_INIT_FLAG" type="xs:boolean">
                                            <xs:annotation>
                                                <xs:documentation>These doodles are initialised
                                                  conditionally based on other clinical information,
                                                  e.g. the operation procedure(s)
                                                  selected.</xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                        <xs:element name="CONDITIONAL_REMOVE_FLAG" type="xs:boolean">
                                            <xs:annotation>
                                                <xs:documentation>These doodles are removed
                                                  conditionally based on other clinical information,
                                                  e.g. the operation procedure(s)
                                                  selected.</xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                        <xs:element name="COMMENT" minOccurs="0">
                                            <xs:annotation>
                                                <xs:documentation>Optional comment on doodle usage
                                                  configuration.</xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="CANVAS_PK">
            <xs:selector xpath="CANVAS_LIST/CANVAS"/>
            <xs:field xpath="CANVAS_MNEMONIC"/>
        </xs:unique>
        <xs:unique name="DOODLE_PK">
            <xs:selector xpath="DOODLE_LIST/DOODLE"/>
            <xs:field xpath="EYEDRAW_CLASS_MNEMONIC"/>
        </xs:unique>
        <xs:keyref name="DOODLE_USAGE_FK1" refer="CANVAS_PK">
            <xs:selector xpath="DOODLE_USAGE_LIST/DOODLE_USAGE"/>
            <xs:field xpath="CANVAS_MNEMONIC"/>
        </xs:keyref>
        <xs:keyref name="DOODLE_USAGE_FK2" refer="DOODLE_PK">
            <xs:selector xpath="DOODLE_USAGE_LIST/DOODLE_USAGE"/>
            <xs:field xpath="EYEDRAW_CLASS_MNEMONIC"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== AppertaFoundation/openeyes/protected/config/core/OE_ED_CONFIG.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 3 (x64) (http://www.altova.com) by Jason Brown (Department of Health and Ageing) -->
<OE_ED_CONFIG xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="OE_ED_CONFIG.xsd">
	<CANVAS_LIST>
		<CANVAS>
			<CANVAS_MNEMONIC>EXAM_ANT_SEG</CANVAS_MNEMONIC>
			<CANVAS_NAME>Examination Anterior Segment</CANVAS_NAME>
			<OE_ELEMENT_CLASS_NAME>OEModule\OphCiExamination\models\Element_OphCiExamination_AnteriorSegment</OE_ELEMENT_CLASS_NAME>
		</CANVAS>
		<CANVAS>
			<CANVAS_MNEMONIC>OP_NOTE_CAT_ANT_SEG</CANVAS_MNEMONIC>
			<CANVAS_NAME>Operation Note Cataract Anterior Segment</CANVAS_NAME>
			<OE_ELEMENT_CLASS_NAME>Element_OphTrOperationnote_Cataract</OE_ELEMENT_CLASS_NAME>
		</CANVAS>
		<CANVAS>
			<CANVAS_MNEMONIC>LASER_ANT_SEG</CANVAS_MNEMONIC>
			<CANVAS_NAME>Laser Anterior Segment</CANVAS_NAME>
			<OE_ELEMENT_CLASS_NAME>Element_OphTrLaser_AnteriorSegment</OE_ELEMENT_CLASS_NAME>
		</CANVAS>
		<CANVAS>
			<CANVAS_MNEMONIC>INJECTION_ANT_SEG</CANVAS_MNEMONIC>
			<CANVAS_NAME>Injection Anterior Segment</CANVAS_NAME>
			<OE_ELEMENT_CLASS_NAME>Element_OphTrIntravitrealinjection_AnteriorSegment</OE_ELEMENT_CLASS_NAME>
		</CANVAS>
	</CANVAS_LIST>
	<DOODLE_LIST>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>ACIOL</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Anterior chamber IOL</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>ACMaintainer</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>AC maintainer</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>AdnexalEye</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Adnexal eye template</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>AngleGrade</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Angle grade</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>AngleGradeEast</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Angle Grade East</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>AngleGradeNorth</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Angle Grade North</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>AngleGradeSouth</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Angle Grade South</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>AngleGradeWest</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Angle Grade West</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>AngleNV</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Angle new vessels</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>AngleRecession</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Angle recession</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>AntPVR</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Anterior PVR</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>AntSeg</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Anterior segment</TITLE>
			<INIT_DOODLE_JSON>{"scaleLevel": 1,"version":1.1,"subclass":"AntSeg","pupilSize":"Large","apexY":-260,"rotation":0,"pxe":false,"coloboma":false,"colour":"Blue","ectropion":false,"cornealSize":"Normal","cells":"Not Checked","flare":"Not Checked","order":1}</INIT_DOODLE_JSON>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>AntSegAngleMarks</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Angle Marks</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>AntSynech</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Anterior synechiae</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>APattern</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>A pattern</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>ArcuateKeratotomy</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Arcuate keratotomy</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>ArcuateScotoma</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Arcuate scotoma</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>Arrow</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Arrow</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>BiopsySite</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Biopsy site</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>Bleb</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Trabeculectomy bleb</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>BlotHaemorrhage</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Blot haemorrhage</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>Buckle</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Buckle</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>BuckleOperation</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Buckle operation</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>BuckleSuture</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Buckle suture</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>BusaccaNodule</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Busacca nodule</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>CapsularTensionRing</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Capsular Tension Ring</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>ChandelierDouble</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Double chandelier</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>ChandelierSingle</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Chandelier</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>ChoroidalHaemorrhage</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Choroidal haemorrhage</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>ChoroidalNaevus</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Choroidal naevus</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>CiliaryInjection</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Cilary injection</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>Circinate</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Circinate retinopathy</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>CircumferentialBuckle</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Circumferential buckle</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>CNV</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Choroidal new vessels</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>ConjunctivalFlap</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Conjunctival flap</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>ConjunctivalSuture</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Conjunctival suture</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>Conjunctivitis</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Conjunctivitis</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>CornealAbrasion</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Corneal abrasion</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>Cornea</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Cornea</TITLE>
			<INIT_DOODLE_JSON>{"scaleLevel":1,"version":1.1,"subclass":"Cornea","shape":"Normal","pachymetry":540,"csOriginX":50,"csApexX":-363,"csApexY":0,"order":0}</INIT_DOODLE_JSON>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>CornealEpithelialDefect</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Corneal epithelial defect</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>CornealErosion</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Removal of corneal epithelium</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>CornealGraft</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Corneal graft</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>CornealInlay</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Corneal inlay</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>CornealOedema</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Corneal oedema</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>CornealOpacity</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Corneal opacity</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>CornealPigmentation</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Corneal pigmentation</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>CornealScar</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Corneal scar</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>CornealStriae</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Corneal striae</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>CornealSuture</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Corneal suture</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>CorticalCataract</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Cortical cataract</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>CottonWoolSpot</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Cotton wool spot</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>Cryo</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Cryotherapy scar</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>CutterPI</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Cutter iridectomy</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>CystoidMacularOedema</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Cystoid macular oedema</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>DendriticUlcer</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Dendritic ulcer</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>DiabeticNV</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Diabetic new vessels</TITLE>
			<INIT_DOODLE_JSON/>
		</DOODLE>
		<DOODLE>
			<EYEDRAW_CLASS_MNEMONIC>Dialysis</EYEDRAW_CLASS_MNEMONIC>
			<TITLE>Dialysis</TITLE>
